/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;
import java.nio.Buffer;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
    
/**
 *
 * @author hoangthang
 */
public class Demo1 extends javax.swing.JFrame {

    /**
     * Creates new form Demo1
     */
    public Demo1() {
        initComponents();
    }
    private int xStart;
    private int yStart;
    private int xEnd;
    private int yEnd;
    
    private Line2D toadoBuffer;
    private Line2D lineBuffer;
    public Ellipse2D circBuffer;
    private Rectangle2D hvBuffer;
    private Rectangle2D hcnBuffer;
    private Ellipse2D elipBuffer;
    private String chuBuffer;
    
    public Color mau = Color.BLACK;
  //  public Graphics g;
    public Graphics2D g2;
    public List<String> chuContainer = new ArrayList();
   public List<Line2D> toadocontainer= new ArrayList();
    public List<Line2D> lineContainer = new ArrayList();
    public List<Ellipse2D> cirContainer = new ArrayList();
    public List<Rectangle2D> hvContainer = new ArrayList();
    public List<Rectangle2D> hcnContainer = new ArrayList();
    public List<Ellipse2D> elipContainer = new ArrayList();
    DefaultComboBoxModel model = new DefaultComboBoxModel();
    public List<Line2D> binhhanhContainer = new ArrayList();
    public List<Line2D> tamgiacContainer = new ArrayList();
    public List<Line2D> xyzContainer = new ArrayList();
    
    // mau sac 
    
    public List<Color> mauLine = new ArrayList();
    public List<Color> mauCir = new ArrayList();
    public List<Color> mauhv = new ArrayList();
    public List<Color> mauellip = new ArrayList();
    public List<Color> mauHcn = new ArrayList();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnHinhBinhHanh = new javax.swing.JButton();
        cbbMauSac = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnVeTruc = new javax.swing.JButton();
        txtVe3D = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnDichTrai = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHIenThi = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jRline = new javax.swing.JRadioButton();
        jRcircle = new javax.swing.JRadioButton();
        jrbHinhVuong = new javax.swing.JRadioButton();
        jRelip = new javax.swing.JRadioButton();
        jRhcn = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        btnClear = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kĩ thuật đồ họa");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/information-icon.png"))); // NOI18N
        jButton2.setText("Hiến Thị");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnHinhBinhHanh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHinhBinhHanh.setText("Hình Bình Hành&Hình Tam Giác");
        btnHinhBinhHanh.setEnabled(false);
        btnHinhBinhHanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHinhBinhHanhActionPerformed(evt);
            }
        });

        cbbMauSac.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbbMauSac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đen", "Đỏ", "Vàng", "Xanh Lá", "Xanh Dương" }));
        cbbMauSac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMauSacActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/draw.png"))); // NOI18N
        jLabel4.setText("Màu sắc: ");

        jPanel2.setBackground(new java.awt.Color(102, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vẽ hình", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 51, 204))); // NOI18N

        btnVeTruc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVeTruc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/250253.png"))); // NOI18N
        btnVeTruc.setText("Vẽ 2D");
        btnVeTruc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeTrucActionPerformed(evt);
            }
        });

        txtVe3D.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtVe3D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3d.png"))); // NOI18N
        txtVe3D.setText("Vẽ 3D");
        txtVe3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVe3DActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVe3D)
                    .addComponent(btnVeTruc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVeTruc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtVe3D)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phép biến đổi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(153, 0, 153))); // NOI18N

        btnDichTrai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDichTrai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/move1.png"))); // NOI18N
        btnDichTrai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDichTraiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDichTrai, javax.swing.GroupLayout.PREFERRED_SIZE, 93, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnDichTrai))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 153, 255))); // NOI18N

        txtHIenThi.setColumns(20);
        txtHIenThi.setRows(5);
        jScrollPane1.setViewportView(txtHIenThi);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        radioGroup.add(jRline);
        jRline.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRline.setForeground(new java.awt.Color(51, 51, 255));
        jRline.setText("Đường thẳng");
        jRline.setEnabled(false);
        jRline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRlineActionPerformed(evt);
            }
        });

        radioGroup.add(jRcircle);
        jRcircle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRcircle.setForeground(new java.awt.Color(255, 51, 51));
        jRcircle.setText("Đường tròn ");
        jRcircle.setEnabled(false);

        radioGroup.add(jrbHinhVuong);
        jrbHinhVuong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrbHinhVuong.setForeground(new java.awt.Color(51, 255, 51));
        jrbHinhVuong.setText("Hình vuông");
        jrbHinhVuong.setEnabled(false);

        radioGroup.add(jRelip);
        jRelip.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRelip.setForeground(new java.awt.Color(255, 255, 153));
        jRelip.setText("Hình elip");
        jRelip.setEnabled(false);
        jRelip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRelipActionPerformed(evt);
            }
        });

        radioGroup.add(jRhcn);
        jRhcn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRhcn.setForeground(new java.awt.Color(0, 255, 255));
        jRhcn.setText("Hình chữ nhật");
        jRhcn.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRcircle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbHinhVuong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRelip)
                .addGap(18, 18, 18)
                .addComponent(jRhcn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRline)
                    .addComponent(jRcircle)
                    .addComponent(jrbHinhVuong)
                    .addComponent(jRelip)
                    .addComponent(jRhcn))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(153, 153, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.svg.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnXoa)
                    .addComponent(btnClear))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(btnClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnXoa))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHinhBinhHanh)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cbbMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)))
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(146, 146, 146)))
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(291, 291, 291)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnHinhBinhHanh)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void put8pixel(Graphics2D g2, int xc, int yc, int x, int y)
{
    g2.drawRect(x + xc, y + yc,1,1);
    g2.drawRect(-x + xc, y + yc, 1,1);
    g2.drawRect(x + xc, -y + yc, 1,1);
    g2.drawRect(-x + xc, -y + yc, 1,1);
    g2.drawRect( y + xc, x + yc, 1,1);
    g2.drawRect(-y + xc, x + yc, 1,1);
    g2.drawRect(y + xc, -x + yc, 1,1);
    g2.drawRect(-y + xc, -x + yc, 1,1);
}
 public void Ellip2d(Graphics2D g2, int xc, int yc, int r)
{
    int x = 0; int y = r;
    int f = 1 - r;
    put8pixel(g2,xc, yc, x, y);
    while (x < y)
    {
        if (f < 0) f += (x << 1) + 3;
        else
        {
            y--;
            f += ((x - y) << 1) + 5;
        }
        x++;
        put8pixel(g2,xc, yc, x, y);
    }
}
    public void putPixel(Graphics2D g, int x, int y)
	{
		g.drawRect(x, y, 1, 1); 
	}
   
    public void Line2d(int x1,int y1,int x2, int y2,Graphics2D g){
       // this.getColor();
        if ((x1 == x2) && (y1 == y2)) {           
        putPixel(g, x1, y1);
        
        } else {              
            int dx = Math.abs(x2 - x1);
            int dy = Math.abs(y2 - y1);
            int rozdil = dx - dy;

            int posun_x, posun_y;

            if (x1 < x2) posun_x = 1; else posun_x = -1;
            if (y1 < y2) posun_y = 1; else posun_y = -1;

            while ((x1 != x2) || (y1 != y2)) {  

                int p = 2 * rozdil;

                if (p > -dy) {
                    rozdil = rozdil - dy;
                    x1 = x1 + posun_x;
                }
                if (p < dx) {
                    rozdil = rozdil + dx;
                    y1 = y1 + posun_y;
                }
                putPixel(g, x1, y1);
            }
        }
    }
    private void jRlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRlineActionPerformed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        if(g2==null)
        {
           
           g2 = (Graphics2D) jPanel1.getGraphics();
        }
        xStart = evt.getX();
        yStart = evt.getY();
        xEnd = evt.getX();
        yEnd = evt.getY();
        
        
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
      g2.setColor(mau);
        if(jRline.isSelected())
        {
               jPanel1.update(g2);
                xEnd = evt.getX();
                yEnd = evt.getY();
                g2.setColor(mau);
                lineBuffer =  new Line2D.Float((float)xStart,(float)yStart,(float)xEnd,(float)yEnd);
              g2.setColor(mau);
                g2.draw(lineBuffer);
                 DrawAll();
                
        }
        if(jRcircle.isSelected())
        {
            jPanel1.update(g2);
            xEnd = evt.getX() - xStart;
            yEnd = evt.getX() - xStart;
            circBuffer = new Ellipse2D.Float((float)xStart,(float)yStart,(float)xEnd,(float)yEnd);
              g2.setColor(mau);
            g2.draw(circBuffer);
          DrawAll();
                
        }
        if(jrbHinhVuong.isSelected())
        {
            jPanel1.update(g2);
            xEnd = evt.getX() - xStart;
            yEnd = evt.getX() - xStart;
            hvBuffer = new Rectangle2D.Float((float)xStart, (float)yStart, (float)xEnd, (float)yEnd);
             g2.setColor(mau);
            DrawAll();
            g2.draw(hvBuffer);
        }
         if(jRelip.isSelected())
        {
            jPanel1.update(g2);
            xEnd = evt.getX() - xStart;
            yEnd = evt.getY() - yStart;
            elipBuffer = new Ellipse2D.Float((float)xStart, (float)yStart, (float)xEnd, (float)yEnd);
             g2.setColor(mau);
            DrawAll();
            g2.draw(elipBuffer);
        }
           if(jRhcn.isSelected())
        {
            jPanel1.update(g2);
            xEnd = evt.getX() - xStart;
            yEnd = evt.getY() - yStart;
            hcnBuffer = new Rectangle2D.Float((float)xStart, (float)yStart, (float)xEnd, (float)yEnd);
            g2.setColor(mau);
            DrawAll();
            g2.draw(hcnBuffer);
        }
        
            
        
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        // TODO add your handling code here:
        //ké rê chuột 
        if(jRline.isSelected())
        {
            jPanel1.update(g2);
            xEnd = evt.getX();
            yEnd = evt.getY();
           lineBuffer =  new Line2D.Float((float)xStart,(float)yStart,(float)xEnd,(float)yEnd);
             mauLine.add(mau);
             lineContainer.add(lineBuffer);
              DrawAll();
        }
         if(jRcircle.isSelected())
        {
            jPanel1.update(g2);
            xEnd = evt.getX()-xStart;
            yEnd = evt.getX()-xStart;
            circBuffer = new Ellipse2D.Float((float)xStart,(float)yStart,(float)xEnd,(float)yEnd);
            mauCir.add(mau);
            cirContainer.add(circBuffer);
            DrawAll();
        }
          if(jrbHinhVuong.isSelected())
        {
            jPanel1.update(g2);
            xEnd = evt.getX() - xStart;
            yEnd = evt.getX() - xStart;
            hvBuffer = new Rectangle2D.Float((float)xStart, (float)yStart, (float)xEnd, (float)yEnd);
            mauhv.add(mau);
            hvContainer.add(hvBuffer);
            DrawAll();
           
        }
             if(jRelip.isSelected())
        {
            jPanel1.update(g2);
            xEnd = evt.getX() - xStart;
            yEnd = evt.getY() - yStart;
            elipBuffer = new Ellipse2D.Float((float)xStart, (float)yStart, (float)xEnd, (float)yEnd);
            mauellip.add(mau);
            elipContainer.add(elipBuffer);
            DrawAll();
            
        }
        if(jRhcn.isSelected())
        {
            jPanel1.update(g2);
            xEnd = evt.getX() - xStart;
            yEnd = evt.getY() - yStart;
            hcnBuffer = new Rectangle2D.Float((float)xStart, (float)yStart, (float)xEnd, (float)yEnd);
             mauHcn.add(mau);
            hcnContainer.add(hcnBuffer);
            DrawAll();
            
            
        }
    }//GEN-LAST:event_jPanel1MouseReleased
frmXuLiDich fdichchuyen = new frmXuLiDich();
    private void btnDichTraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDichTraiActionPerformed
        // TODO add your handling code here:
        if((lineContainer.isEmpty()||lineContainer.size()<=2)&&elipContainer.isEmpty()
           &&cirContainer.isEmpty()&&hvContainer.isEmpty()&&hcnContainer.isEmpty())
        {
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa vẽ cái gì ");
        }
        else{
       fdichchuyen.setjpanel(jPanel1);
       fdichchuyen.setFrmDemo(this);
        fdichchuyen.SetContainerLine(lineContainer);
        fdichchuyen.SetContainerCirle(cirContainer);
        fdichchuyen.setVisible(true);
        fdichchuyen.setG2(g2);
        }
    }//GEN-LAST:event_btnDichTraiActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //txtHIenThi.setText("Chao ban");
          String show1 = "";
        if(jRline.isSelected()){
             show1 += "-- Đường thẳng--\n";
            for(int i=2;i<lineContainer.size();i++){
                int j=i+1;
                double a,b;
                show1 +="Đường thẳng số "+(j-2) +"\n";
                a = ChuyenX((float) lineContainer.get(i).getX1());
                b = ChuyenY((float) lineContainer.get(i).getY1());
                show1 +="Điểm đầu :"+a+","+b+"\n";
                a = ChuyenX((float) lineContainer.get(i).getX2());
                b = ChuyenY((float) lineContainer.get(i).getY2());
                show1 +="Điểm cuối:"+a+","+b+"\n";
            }
        }
        if(jRhcn.isSelected()){
             show1 += "-- Hình Chữ Nhật --\n";
            for(int i=0;i<hcnContainer.size();i++){
                int j=i+1;
                show1 +="Hình chữ nhật số "+j+"\n";
                show1 +="Điểm đỉnh trái: "+ChuyenX((float) hcnContainer.get(i).getX())+","+ChuyenY((float) hcnContainer.get(i).getY())+"\n";
                double d = (hcnContainer.get(i).getCenterX()-hcnContainer.get(i).getX())*2;
                show1 +="Chiều dài :"+d+"\n";
                double r = (hcnContainer.get(i).getCenterY()-hcnContainer.get(i).getY())*2;
                show1 +="Chiều rộng :"+r+"\n";               
            }
        }
       if(jrbHinhVuong.isSelected()){
            show1 += "-- Hình Vuông --\n";
            for(int i=0;i<hvContainer.size();i++){
                int j=i+1;
                show1 +="Hình chữ nhật số "+j+"\n";
                show1 +="Điểm đỉnh trái: "+ChuyenX((float) hvContainer.get(i).getX())+","+ChuyenY((float) hvContainer.get(i).getY())+"\n";
             //   double d = Chinh_So_X((rectContainer_1.get(i).getCenterX()-rectContainer_1.get(i).getX())*2);
                double d = (hvContainer.get(i).getCenterX()-hvContainer.get(i).getX())*2;
                show1 +="Chiều dài cạnh :"+d+"\n";
                          
            }
        }
       if(jRcircle.isSelected()){
            show1 += "-- Hình Tròn --\n";
            for(int i=0;i<cirContainer.size();i++){
                int j=i+1;
                show1+="Hình tròn số "+j+"\n";
                show1+="Tâm      : "+ChuyenX((float) cirContainer.get(i).getCenterX())+","+ChuyenY((float) cirContainer.get(i).getCenterY())+"\n";
                show1+="Bán kính : "+(int)(cirContainer.get(i).getHeight())/2 +"\n";
            }
        }
        if(jRelip.isSelected()){
            show1 += "-- Hình Elip --\n";
            for(int i=0;i<elipContainer.size();i++){
                int j=i+1;
                show1+="Hình tròn số "+j+"\n";
                show1+="Tâm      : "+ChuyenX((float) elipContainer.get(i).getCenterX())+","+ChuyenY((float) elipContainer.get(i).getCenterY())+"\n";
                show1+="Chiều cao : "+(int)(elipContainer.get(i).getHeight())/2 +"\n";
                show1+="Chiều rộng : "+(int)(elipContainer.get(i).getHeight())/2 +"\n";
            }
        }
     //   frameLuaChonHH1.setVisible(true);*/
        txtHIenThi.setText(show1);
    }//GEN-LAST:event_jButton2ActionPerformed
    private frmHBH frhbh = new frmHBH();
    private void btnHinhBinhHanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHinhBinhHanhActionPerformed
        // TODO add your handling code here:
      
        if(g2==null)
        {
           g2 = (Graphics2D) jPanel1.getGraphics();
        }
        frhbh.setG2(g2);
        frhbh.setjpanel(jPanel1);
        frhbh.setFrmDemo(this);
        frhbh.setVisible(true);
        
    }//GEN-LAST:event_btnHinhBinhHanhActionPerformed
   private frmve3D frve3D = new frmve3D();
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        jPanel1.update(g2);
        cirContainer.clear();
        elipContainer.clear();
        lineContainer.clear();
        mauLine.clear();
     //   mauLine.add(Color.BLACK);
      //  mauLine.add(Color.BLACK);
        mauCir.clear();
        mauHcn.clear();
        mauellip.clear();
        mauhv.clear();
         //public List<Line2D> lineContainer = new ArrayList();
   // public List<Ellipse2D> cirContainer = new ArrayList();
    hvContainer.clear();
    hcnContainer.clear();
    //public List<Ellipse2D> elipContainer = new ArrayList();
    //DefaultComboBoxModel model = new DefaultComboBoxModel();
     binhhanhContainer.clear();
    tamgiacContainer.clear();
    frve3D.hhcnContainer.clear();
    frve3D.hcContainer.clear();
             xyzContainer.clear();

    }//GEN-LAST:event_btnClearActionPerformed

    private void jRelipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRelipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRelipActionPerformed

    private void btnVeTrucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeTrucActionPerformed
        // TODO add your handling code here:
      
        jRline.setEnabled(true);
        jRcircle.setEnabled(true);
        jRelip.setEnabled(true);
        jRhcn.setEnabled(true);
        jrbHinhVuong.setEnabled(true); 
        btnHinhBinhHanh.setEnabled(true);
        //truc oy
    
       // jPanel1.update(g2);
       
        lineBuffer = new Line2D.Float(250, 0, 250, 500);
        lineContainer.add(lineBuffer);
        for(int i = 0 ;i<50;i++){
         toadoBuffer = new Line2D.Float(10+10*i, 245, 10+10*i, 255);
        toadocontainer.add(toadoBuffer);
        toadoBuffer = new Line2D.Float(245, 10+10*i, 255, 10+10*i);
        toadocontainer.add(toadoBuffer);
        }
        
         lineBuffer = new Line2D.Float(0, 250, 500, 250);
        lineContainer.add(lineBuffer);
        mauLine.add(Color.BLACK);
        mauLine.add(Color.BLACK);
        chuContainer.add(chuBuffer);
        //g.drawString("))))))))", 50, 50);
       
         if(g2==null)
        {
           g2 = (Graphics2D) jPanel1.getGraphics();
        }
        DrawAll();
        
    }//GEN-LAST:event_btnVeTrucActionPerformed
    frmve3D frmhh = new frmve3D();
    private void txtVe3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVe3DActionPerformed
        // TODO add your handling code here:
        
        if(g2==null)
        {
           g2 = (Graphics2D) jPanel1.getGraphics();
        }
        xyzContainer.clear();
        lineBuffer = new Line2D.Float(250, 250, 250, 0);
        xyzContainer.add(lineBuffer);//0y
        lineBuffer = new Line2D.Float(250, 250, 500, 250);
        xyzContainer.add(lineBuffer);//ox
        lineBuffer = new Line2D.Float(250, 250, 0, 500);
        xyzContainer.add(lineBuffer);//0z
        
        frmhh.setG2(g2);
        frmhh.setjpanel(jPanel1);
        frmhh.setFrmDemo(this);
        frmhh.setVisible(true);
        
    }//GEN-LAST:event_txtVe3DActionPerformed

    private void cbbMauSacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMauSacActionPerformed
        // TODO add your handling code here:
         int thutu;
        thutu = cbbMauSac.getSelectedIndex();  
        switch (thutu){
            case 0 : mau = Color.BLACK;//den do vang la duong
            break;
            case 1 : mau = Color.RED;
            break;
            case 2 : mau = Color.YELLOW;
            break;
            case 3 : mau = Color.GREEN;
            break;
            case 4 : mau = Color.BLUE;
            break;
        }
    }//GEN-LAST:event_cbbMauSacActionPerformed
    frmXoa fxoa = new frmXoa();
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        fxoa.setGraphic(g2);
        fxoa.setJP(jPanel1);
        fxoa.setform(this);
        fxoa.setVisible(true);
    
   
       
    }//GEN-LAST:event_btnXoaActionPerformed
    public float ChuyenX(float x)
    {
       
        return x - 250;
        
    }
    public float ChuyenY(float y)
    {
       
        return 250-y ;
    }
    public void DrawAll()
    {
        g2.setColor(mauLine.get(0));
         g2.draw(lineContainer.get(0));
         g2.setColor(mauLine.get(1));
          g2.draw(lineContainer.get(1));
        for(int i = 2 ; i < lineContainer.size();i++)
        {
            g2.setColor(mauLine.get(i));
            g2.draw(lineContainer.get(i));
            
             
        }
          for(int i = 0 ;i< toadocontainer.size();i++)
        {
           g2.setColor(Color.BLACK);
            g2.draw(toadocontainer.get(i));
        }
            for(int i = 0 ;i< chuContainer.size();i++)
        {
          g2.setColor(Color.BLACK);
            g2.drawString("O",255,265);
            g2.drawString("X", 490, 265);
            g2.drawString("Y", 255, 10);
        }
        for(int i = 0 ;i< cirContainer.size();i++)
        {
            g2.setColor(mauCir.get(i));
            g2.draw(cirContainer.get(i));
        }
         
        for(int i=0;i<hvContainer.size();i++)
        {
              g2.setColor(mauhv.get(i));
           g2.draw(hvContainer.get(i));
        }
        for(int i = 0 ; i< binhhanhContainer.size();i++)
        {
            g2.draw(binhhanhContainer.get(i));
        }
         for(int i = 0 ; i< tamgiacContainer.size();i++)
        {
            g2.draw(tamgiacContainer.get(i));
        }
        for(int i = 0 ; i< elipContainer.size();i++)
        {
              g2.setColor(mauellip.get(i));
            g2.draw(elipContainer.get(i));
        }
        for(int i = 0 ; i< hcnContainer.size();i++)
        {
              g2.setColor(mauHcn.get(i));
            g2.draw(hcnContainer.get(i));
        }
    }
    /**
     * @param args the command line arguments
     */
      public Line2D line2D(int x1,int y1,int x2, int y2,Graphics2D g){
       return new Line2D.Float((float)x1,(float)y1,(float)x2,(float)y2);
   }
    public Ellipse2D ellipse2D(int g2, int xc, int yc, int r){
       return new Ellipse2D.Float((float)g2,(float)xc,(float)yc,(float)r);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Demo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Demo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Demo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Demo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Demo1().setVisible(true);
            }
        });
    }
    javax.swing.JRadioButton getRadioCir(){
        return jRcircle;
    }
    javax.swing.JRadioButton getRadioEllip(){
        return jRelip;
    }
    javax.swing.JRadioButton getRadioHcn(){
        return jRhcn;
    }
    javax.swing.JRadioButton getRadioLine(){
        return jRline;
    }
     javax.swing.JRadioButton getRadioHv(){
        return jrbHinhVuong;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDichTrai;
    private javax.swing.JButton btnHinhBinhHanh;
    private javax.swing.JButton btnVeTruc;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbMauSac;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRcircle;
    private javax.swing.JRadioButton jRelip;
    private javax.swing.JRadioButton jRhcn;
    private javax.swing.JRadioButton jRline;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrbHinhVuong;
    private javax.swing.ButtonGroup radioGroup;
    private javax.swing.JTextArea txtHIenThi;
    private javax.swing.JButton txtVe3D;
    // End of variables declaration//GEN-END:variables
}
