/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo;

import java.awt.Graphics2D;
import java.awt.geom.Line2D;
import javax.swing.JPanel;

/**
 *
 * @author hoangthang
 */
public class frmHBH extends javax.swing.JFrame {

    /**
     * Creates new form frmHBH
     */
    public frmHBH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtX1 = new javax.swing.JTextField();
        txtY1 = new javax.swing.JTextField();
        txtX2 = new javax.swing.JTextField();
        txtY2 = new javax.swing.JTextField();
        txtD = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtxA = new javax.swing.JTextField();
        txtyA = new javax.swing.JTextField();
        txtxB = new javax.swing.JTextField();
        txtyB = new javax.swing.JTextField();
        txtxC = new javax.swing.JTextField();
        txtYc = new javax.swing.JTextField();
        btnVeTamGiac = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnDichTrai = new javax.swing.JButton();
        btnDichPhai = new javax.swing.JButton();
        txtChonLua = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtdoDich = new javax.swing.JTextField();
        btnDichLen = new javax.swing.JButton();
        btnDichXuong = new javax.swing.JButton();
        btnDxOX = new javax.swing.JButton();
        btnDxOY = new javax.swing.JButton();
        btnDxQT = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtChiSo = new javax.swing.JTextField();
        txtChonHinh = new javax.swing.JTextField();
        btnDT = new javax.swing.JButton();
        btnDP = new javax.swing.JButton();
        btnDL = new javax.swing.JButton();
        btnDX = new javax.swing.JButton();
        btnDXX = new javax.swing.JButton();
        btnDXY = new javax.swing.JButton();
        btnDXT = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Toa do A");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Toa do C");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Do dai D");

        txtX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtX1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/270f.png"))); // NOI18N
        jButton1.setText("Vẽ ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(38, 38, 38)
                        .addComponent(txtD))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtX1)
                            .addComponent(txtX2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtY1)
                            .addComponent(txtY2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hình bình hành", jPanel1);

        jLabel4.setText("Tọa độ A");

        jLabel5.setText("Tọa độ B");

        jLabel6.setText("Tọa độ C");

        txtxA.setText("10");

        txtyA.setText("20");

        txtxB.setText("50");

        txtyB.setText("60");

        txtxC.setText("90");

        txtYc.setText("70");

        btnVeTamGiac.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVeTamGiac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/270f.png"))); // NOI18N
        btnVeTamGiac.setText("Vẽ ");
        btnVeTamGiac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeTamGiacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtxC))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtxB))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtxA, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVeTamGiac)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtyB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtyA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtxA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtyA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtxB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtyB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtxC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtYc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnVeTamGiac)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tam giác", jPanel2);

        btnDichTrai.setText("Dịch trái");
        btnDichTrai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDichTraiActionPerformed(evt);
            }
        });

        btnDichPhai.setText("Dịch phải ");
        btnDichPhai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDichPhaiActionPerformed(evt);
            }
        });

        jLabel7.setText("Chọn lựa");

        jLabel8.setText("Độ dịch");

        btnDichLen.setText("Dịch lên");
        btnDichLen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDichLenActionPerformed(evt);
            }
        });

        btnDichXuong.setText("Dịch xuống");
        btnDichXuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDichXuongActionPerformed(evt);
            }
        });

        btnDxOX.setText("Đối xứng qua Ox");
        btnDxOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDxOXActionPerformed(evt);
            }
        });

        btnDxOY.setText("Đối xứng qua Oy");
        btnDxOY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDxOYActionPerformed(evt);
            }
        });

        btnDxQT.setText("Đối xứng qua tâm");
        btnDxQT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDxQTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDichTrai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDichPhai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDxQT))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnDichLen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDichXuong))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtdoDich, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtChonLua, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnDxOX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDxOY)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtChonLua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdoDich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDxOX)
                    .addComponent(btnDxOY))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDichTrai)
                    .addComponent(btnDichPhai)
                    .addComponent(btnDxQT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDichLen)
                    .addComponent(btnDichXuong))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tịnh tiến HBH", jPanel3);

        jLabel9.setText("Chỉ Số");

        jLabel10.setText("Chọn Hình");

        btnDT.setText("Dịch Trái");
        btnDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDTActionPerformed(evt);
            }
        });

        btnDP.setText("Dịch Phải");
        btnDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDPActionPerformed(evt);
            }
        });

        btnDL.setText("Dịch Lên");
        btnDL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDLActionPerformed(evt);
            }
        });

        btnDX.setText("Dịch Xuống");
        btnDX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDXActionPerformed(evt);
            }
        });

        btnDXX.setText("Đối xứng qua Ox");
        btnDXX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDXXActionPerformed(evt);
            }
        });

        btnDXY.setText("Đối xứng qua Oy");
        btnDXY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDXYActionPerformed(evt);
            }
        });

        btnDXT.setText("Đối Xứng Qua Tâm");
        btnDXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDXTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtChonHinh))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(35, 35, 35)
                                .addComponent(txtChiSo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDT)
                        .addGap(18, 18, 18)
                        .addComponent(btnDP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDL))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDX)
                        .addGap(18, 18, 18)
                        .addComponent(btnDXX))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDXT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDXY)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtChiSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtChonHinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDT)
                    .addComponent(btnDP)
                    .addComponent(btnDL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDX)
                    .addComponent(btnDXX))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDXT)
                    .addComponent(btnDXY))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tịnh Tiến Tam Giác", jPanel4);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        jButton8.setText("Thoát");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtX1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtX1ActionPerformed
       private JPanel _jp;
    public void setjpanel(JPanel jp)
    {
        _jp=jp;
    }
    private Demo1 _demo1;
    public void setFrmDemo(Demo1 d1)
    {
        _demo1 = d1;
    }
   private Line2D lineBuffer;
    Graphics2D _g2;
    public void setG2(Graphics2D g2){
        _g2 = g2;
    }
    private void DrawHBH(int x1,int y1,int x2,int y2,int d)
    {
       // _demo1.binhhanhContainer.clear();
        int x3 = x1+d,x4 = x2 - d;
        int y3 = y1,y4 = y2;
        lineBuffer = new Line2D.Float((float)x1, (float)y1, (float)x3, (float)y3);
        _demo1.binhhanhContainer.add(lineBuffer);
        lineBuffer = new Line2D.Float((float)x3, (float)y3,(float) x2,(float) y2);
        _demo1.binhhanhContainer.add(lineBuffer);
        lineBuffer= new Line2D.Float((float)x2, (float)y2, (float)x4,(float) y4);
        _demo1.binhhanhContainer.add(lineBuffer);
        lineBuffer= new Line2D.Float((float)x4, (float)y4, (float)x1, (float)y1);
        _demo1.binhhanhContainer.add(lineBuffer);

        _jp.update(_g2);
       _demo1.DrawAll();  
        
    }
    private void DrawTamGiac(int x1,int y1,int x2,int y2,int x3,int y3)
    {
        lineBuffer = new Line2D.Float((float)x1, (float)y1, (float)x2, (float)y2);
        _demo1.tamgiacContainer.add(lineBuffer);
          lineBuffer = new Line2D.Float((float)x2, (float)y2, (float)x3, (float)y3);
        _demo1.tamgiacContainer.add(lineBuffer);
        
          lineBuffer = new Line2D.Float((float)x3, (float)y3, (float)x1, (float)y1);
        _demo1.tamgiacContainer.add(lineBuffer);
           _jp.update(_g2);
       _demo1.DrawAll();
    }
     public int ChuyenX(int x)
    {
        
            return  x + 250;
        
  
      
     }
    public int ChuyenY(int y)
    {
       
       
          return   250-y;
      
        
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int x1 = Integer.parseInt(txtX1.getText());
            int y1 = Integer.parseInt(txtY1.getText());
          int x2 = Integer.parseInt(txtX2.getText());
            int y2 = Integer.parseInt(txtY2.getText());
            int d = Integer.parseInt(txtD.getText());
            int x = ChuyenX(x1);
            int y = ChuyenY(y1);
            int z = ChuyenX(x2);
            int t = ChuyenY(y2);
            DrawHBH(x, y, z, t, d);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnVeTamGiacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeTamGiacActionPerformed
        // TODO add your handling code here:
        int xA = Integer.parseInt(txtxA.getText());
        int yA = Integer.parseInt(txtyA.getText());
         int xB = Integer.parseInt(txtxB.getText());
        int yB = Integer.parseInt(txtyB.getText());
         int xC = Integer.parseInt(txtxC.getText());
        int yC= Integer.parseInt(txtYc.getText());
        int xAC = ChuyenX(xA);
        int yAC = ChuyenY(yA);
         int xBC = ChuyenX(xB);
        int yBC = ChuyenY(yB);
         int xCC = ChuyenX(xC);
        int yCC = ChuyenY(yC);
        DrawTamGiac(xAC,yAC,xBC,yBC,xCC,yCC);
    }//GEN-LAST:event_btnVeTamGiacActionPerformed

    private void btnDichTraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDichTraiActionPerformed
        // TODO add your handling code here:
        int doDich = Integer.parseInt(txtdoDich.getText());
     int chonLua = 4*(Integer.parseInt(txtChonLua.getText())-1);
        // chonLua+=2;
        
            Line2D l = _demo1.binhhanhContainer.get(chonLua);
            l.setLine(l.getX1()+doDich, l.getY1(), l.getX2()+doDich, l.getY2());
            _demo1.binhhanhContainer.set(chonLua, l);
             Line2D l1 = _demo1.binhhanhContainer.get(chonLua+1);
            l1.setLine(l1.getX1()+doDich, l1.getY1(), l1.getX2()+doDich, l1.getY2());
            _demo1.binhhanhContainer.set(chonLua+1, l1);
               Line2D l2 = _demo1.binhhanhContainer.get(chonLua+2);
            l2.setLine(l2.getX1()+doDich, l2.getY1(), l2.getX2()+doDich, l2.getY2());
            _demo1.binhhanhContainer.set(chonLua+2, l2);
               Line2D l3 = _demo1.binhhanhContainer.get(chonLua+3);
            l3.setLine(l3.getX1()+doDich, l3.getY1(), l3.getX2()+doDich, l3.getY2());
            _demo1.binhhanhContainer.set(chonLua+3, l3);
            _jp.update(_g2);
            _demo1.DrawAll();
        
    }//GEN-LAST:event_btnDichTraiActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnDichPhaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDichPhaiActionPerformed
        // TODO add your handling code here:
         int doDich = Integer.parseInt(txtdoDich.getText());
       int chonLua = 4*(Integer.parseInt(txtChonLua.getText())-1);
        // chonLua+=2;
        
            Line2D l = _demo1.binhhanhContainer.get(chonLua);
            l.setLine(l.getX1()-doDich, l.getY1(), l.getX2()-doDich, l.getY2());
            _demo1.binhhanhContainer.set(chonLua, l);
             Line2D l1 = _demo1.binhhanhContainer.get(chonLua+1);
            l1.setLine(l1.getX1()-doDich, l1.getY1(), l1.getX2()-doDich, l1.getY2());
            _demo1.binhhanhContainer.set(chonLua+1, l1);
               Line2D l2 = _demo1.binhhanhContainer.get(chonLua+2);
            l2.setLine(l2.getX1()-doDich, l2.getY1(), l2.getX2()-doDich, l2.getY2());
            _demo1.binhhanhContainer.set(chonLua+2, l2);
               Line2D l3 = _demo1.binhhanhContainer.get(chonLua+3);
            l3.setLine(l3.getX1()-doDich, l3.getY1(), l3.getX2()-doDich, l3.getY2());
            _demo1.binhhanhContainer.set(chonLua+3, l3);
            _jp.update(_g2);
            _demo1.DrawAll();
    }//GEN-LAST:event_btnDichPhaiActionPerformed

    private void btnDichLenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDichLenActionPerformed
        // TODO add your handling code here:
         int doDich = Integer.parseInt(txtdoDich.getText());
    int chonLua = 4*(Integer.parseInt(txtChonLua.getText())-1);
        // chonLua+=2;
        
            Line2D l = _demo1.binhhanhContainer.get(chonLua);
            l.setLine(l.getX1(), l.getY1()-doDich, l.getX2(), l.getY2()-doDich);
            _demo1.binhhanhContainer.set(chonLua, l);
             Line2D l1 = _demo1.binhhanhContainer.get(chonLua+1);
            l1.setLine(l1.getX1(), l1.getY1()-doDich, l1.getX2(), l1.getY2()-doDich);
            _demo1.binhhanhContainer.set(chonLua+1, l1);
               Line2D l2 = _demo1.binhhanhContainer.get(chonLua+2);
            l2.setLine(l2.getX1(), l2.getY1()-doDich, l2.getX2(), l2.getY2()-doDich);
            _demo1.binhhanhContainer.set(chonLua+2, l2);
               Line2D l3 = _demo1.binhhanhContainer.get(chonLua+3);
            l3.setLine(l3.getX1(), l3.getY1()-doDich, l3.getX2(), l3.getY2()-doDich);
            _demo1.binhhanhContainer.set(chonLua+3, l3);
            _jp.update(_g2);
            _demo1.DrawAll();
    }//GEN-LAST:event_btnDichLenActionPerformed

    private void btnDichXuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDichXuongActionPerformed
        // TODO add your handling code here:
          int doDich = Integer.parseInt(txtdoDich.getText());
     int chonLua = 4*(Integer.parseInt(txtChonLua.getText())-1);
        // chonLua+=2;
        
            Line2D l = _demo1.binhhanhContainer.get(chonLua);
            l.setLine(l.getX1(), l.getY1()+doDich, l.getX2(), l.getY2()+doDich);
            _demo1.binhhanhContainer.set(chonLua, l);
             Line2D l1 = _demo1.binhhanhContainer.get(chonLua+1);
            l1.setLine(l1.getX1(), l1.getY1()+doDich, l1.getX2(), l1.getY2()+doDich);
            _demo1.binhhanhContainer.set(chonLua+1, l1);
               Line2D l2 = _demo1.binhhanhContainer.get(chonLua+2);
            l2.setLine(l2.getX1(), l2.getY1()+doDich, l2.getX2(), l2.getY2()+doDich);
            _demo1.binhhanhContainer.set(chonLua+2, l2);
               Line2D l3 = _demo1.binhhanhContainer.get(chonLua+3);
            l3.setLine(l3.getX1(), l3.getY1()+doDich, l3.getX2(), l3.getY2()+doDich);
            _demo1.binhhanhContainer.set(chonLua+3, l3);
            _jp.update(_g2);
            _demo1.DrawAll();
    }//GEN-LAST:event_btnDichXuongActionPerformed

    private void btnDxOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDxOXActionPerformed
        // TODO add your handling code here:
    //      int doDich = Integer.parseInt(txtdoDich.getText());
        int chonLua = 4*(Integer.parseInt(txtChonLua.getText())-1);
        // chonLua+=2;
        
            Line2D l = _demo1.binhhanhContainer.get(chonLua);
            l.setLine(l.getX1(), 499- l.getY1(), l.getX2(), 499- l.getY2());
            _demo1.binhhanhContainer.set(chonLua, l);
             Line2D l1 = _demo1.binhhanhContainer.get(chonLua+1);
            l1.setLine(l1.getX1(),499- l1.getY1(), l1.getX2(), 499-l1.getY2());
            _demo1.binhhanhContainer.set(chonLua+1, l1);
               Line2D l2 = _demo1.binhhanhContainer.get(chonLua+2);
            l2.setLine(l2.getX1(),499- l2.getY1(), l2.getX2(),499- l2.getY2());
            _demo1.binhhanhContainer.set(chonLua+2, l2);
               Line2D l3 = _demo1.binhhanhContainer.get(chonLua+3);
            l3.setLine(l3.getX1(),499- l3.getY1(), l3.getX2(),499- l3.getY2());
            _demo1.binhhanhContainer.set(chonLua+3, l3);
            _jp.update(_g2);
            _demo1.DrawAll();
    }//GEN-LAST:event_btnDxOXActionPerformed

    private void btnDxOYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDxOYActionPerformed
        // TODO add your handling code here:
        int chonLua = 4*(Integer.parseInt(txtChonLua.getText())-1);
        // chonLua+=2;
        
            Line2D l = _demo1.binhhanhContainer.get(chonLua);
            l.setLine(499-l.getX1(),  l.getY1(),499- l.getX2(),  l.getY2());
            _demo1.binhhanhContainer.set(chonLua, l);
             Line2D l1 = _demo1.binhhanhContainer.get(chonLua+1);
            l1.setLine(499-l1.getX1(),l1.getY1(),499- l1.getX2(), l1.getY2());
            _demo1.binhhanhContainer.set(chonLua+1, l1);
               Line2D l2 = _demo1.binhhanhContainer.get(chonLua+2);
            l2.setLine(499-l2.getX1(), l2.getY1(),499- l2.getX2(), l2.getY2());
            _demo1.binhhanhContainer.set(chonLua+2, l2);
               Line2D l3 = _demo1.binhhanhContainer.get(chonLua+3);
            l3.setLine(499-l3.getX1(), l3.getY1(),499- l3.getX2(), l3.getY2());
            _demo1.binhhanhContainer.set(chonLua+3, l3);
            _jp.update(_g2);
            _demo1.DrawAll();
    }//GEN-LAST:event_btnDxOYActionPerformed

    private void btnDxQTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDxQTActionPerformed
        // TODO add your handling code here:
           int chonLua = 4*(Integer.parseInt(txtChonLua.getText())-1);
        // chonLua+=2;
        
            Line2D l = _demo1.binhhanhContainer.get(chonLua);
            l.setLine(499-l.getX1(), 499- l.getY1(),499- l.getX2(),  499-l.getY2());
            _demo1.binhhanhContainer.set(chonLua, l);
             Line2D l1 = _demo1.binhhanhContainer.get(chonLua+1);
            l1.setLine(499-l1.getX1(),499-l1.getY1(),499- l1.getX2(), 499-l1.getY2());
            _demo1.binhhanhContainer.set(chonLua+1, l1);
               Line2D l2 = _demo1.binhhanhContainer.get(chonLua+2);
            l2.setLine(499-l2.getX1(),499- l2.getY1(),499- l2.getX2(), 499-l2.getY2());
            _demo1.binhhanhContainer.set(chonLua+2, l2);
               Line2D l3 = _demo1.binhhanhContainer.get(chonLua+3);
            l3.setLine(499-l3.getX1(), 499-l3.getY1(),499- l3.getX2(),499- l3.getY2());
            _demo1.binhhanhContainer.set(chonLua+3, l3);
            _jp.update(_g2);
            _demo1.DrawAll();
    }//GEN-LAST:event_btnDxQTActionPerformed

    private void btnDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDTActionPerformed
        // TODO add your handling code here:
           int doDich = Integer.parseInt(txtChiSo.getText());
           int chonLua = 3*(Integer.parseInt(txtChonHinh.getText())-1);
        // chonLua+=2;
        
            Line2D l = _demo1.tamgiacContainer.get(chonLua);
            l.setLine(l.getX1()-doDich, l.getY1(), l.getX2()-doDich, l.getY2());
            _demo1.tamgiacContainer.set(chonLua, l);
             Line2D l1 = _demo1.tamgiacContainer.get(chonLua+1);
            l1.setLine(l1.getX1()-doDich, l1.getY1(), l1.getX2()-doDich, l1.getY2());
            _demo1.tamgiacContainer.set(chonLua+1, l1);
               Line2D l2 = _demo1.tamgiacContainer.get(chonLua+2);
            l2.setLine(l2.getX1()-doDich, l2.getY1(), l2.getX2()-doDich, l2.getY2());
            _demo1.tamgiacContainer.set(chonLua+2, l2);
            _jp.update(_g2);
            _demo1.DrawAll();
    }//GEN-LAST:event_btnDTActionPerformed

    private void btnDLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDLActionPerformed
        // TODO add your handling code here:
           int doDich = Integer.parseInt(txtChiSo.getText());
           int chonLua = 3*(Integer.parseInt(txtChonHinh.getText())-1);
        // chonLua+=2;
        
            Line2D l = _demo1.tamgiacContainer.get(chonLua);
            l.setLine(l.getX1(), l.getY1()-doDich, l.getX2(), l.getY2()-doDich);
            _demo1.tamgiacContainer.set(chonLua, l);
             Line2D l1 = _demo1.tamgiacContainer.get(chonLua+1);
            l1.setLine(l1.getX1(), l1.getY1()-doDich, l1.getX2(), l1.getY2()-doDich);
            _demo1.tamgiacContainer.set(chonLua+1, l1);
               Line2D l2 = _demo1.tamgiacContainer.get(chonLua+2);
            l2.setLine(l2.getX1(), l2.getY1()-doDich, l2.getX2(), l2.getY2()-doDich);
            _demo1.tamgiacContainer.set(chonLua+2, l2);
            _jp.update(_g2);
            _demo1.DrawAll();
    }//GEN-LAST:event_btnDLActionPerformed

    private void btnDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDPActionPerformed
        // TODO add your handling code here:
         int doDich = Integer.parseInt(txtChiSo.getText());
           int chonLua = 3*(Integer.parseInt(txtChonHinh.getText())-1);
        // chonLua+=2;
        
            Line2D l = _demo1.tamgiacContainer.get(chonLua);
            l.setLine(l.getX1()+doDich, l.getY1(), l.getX2()+doDich, l.getY2());
            _demo1.tamgiacContainer.set(chonLua, l);
             Line2D l1 = _demo1.tamgiacContainer.get(chonLua+1);
            l1.setLine(l1.getX1()+doDich, l1.getY1(), l1.getX2()+doDich, l1.getY2());
            _demo1.tamgiacContainer.set(chonLua+1, l1);
               Line2D l2 = _demo1.tamgiacContainer.get(chonLua+2);
            l2.setLine(l2.getX1()+doDich, l2.getY1(), l2.getX2()+doDich, l2.getY2());
            _demo1.tamgiacContainer.set(chonLua+2, l2);
            _jp.update(_g2);
            _demo1.DrawAll();
    }//GEN-LAST:event_btnDPActionPerformed

    private void btnDXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDXActionPerformed
        // TODO add your handling code here:
        int doDich = Integer.parseInt(txtChiSo.getText());
           int chonLua = 3*(Integer.parseInt(txtChonHinh.getText())-1);
        // chonLua+=2;
        
            Line2D l = _demo1.tamgiacContainer.get(chonLua);
            l.setLine(l.getX1(), l.getY1()+doDich, l.getX2(), l.getY2()+doDich);
            _demo1.tamgiacContainer.set(chonLua, l);
             Line2D l1 = _demo1.tamgiacContainer.get(chonLua+1);
            l1.setLine(l1.getX1(), l1.getY1()+doDich, l1.getX2(), l1.getY2()+doDich);
            _demo1.tamgiacContainer.set(chonLua+1, l1);
               Line2D l2 = _demo1.tamgiacContainer.get(chonLua+2);
            l2.setLine(l2.getX1(), l2.getY1()+doDich, l2.getX2(), l2.getY2()+doDich);
            _demo1.tamgiacContainer.set(chonLua+2, l2);
            _jp.update(_g2);
            _demo1.DrawAll();
    }//GEN-LAST:event_btnDXActionPerformed

    private void btnDXXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDXXActionPerformed
        // TODO add your handling code here:
         int doDich = Integer.parseInt(txtChiSo.getText());
           int chonLua = 3*(Integer.parseInt(txtChonHinh.getText())-1);
        // chonLua+=2;
        
            Line2D l = _demo1.tamgiacContainer.get(chonLua);
            l.setLine(l.getX1(),499- l.getY1(), l.getX2(), 499-l.getY2());
            _demo1.tamgiacContainer.set(chonLua, l);
             Line2D l1 = _demo1.tamgiacContainer.get(chonLua+1);
            l1.setLine(l1.getX1(),499- l1.getY1(), l1.getX2(),499- l1.getY2());
            _demo1.tamgiacContainer.set(chonLua+1, l1);
               Line2D l2 = _demo1.tamgiacContainer.get(chonLua+2);
            l2.setLine(l2.getX1(),499- l2.getY1(), l2.getX2(), 499 - l2.getY2());
            _demo1.tamgiacContainer.set(chonLua+2, l2);
            _jp.update(_g2);
            _demo1.DrawAll();
    }//GEN-LAST:event_btnDXXActionPerformed

    private void btnDXYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDXYActionPerformed
        // TODO add your handling code here:
          int doDich = Integer.parseInt(txtChiSo.getText());
           int chonLua = 3*(Integer.parseInt(txtChonHinh.getText())-1);
        // chonLua+=2;
        
            Line2D l = _demo1.tamgiacContainer.get(chonLua);
            l.setLine(499-l.getX1(), l.getY1(),499- l.getX2(),l.getY2());
            _demo1.tamgiacContainer.set(chonLua, l);
             Line2D l1 = _demo1.tamgiacContainer.get(chonLua+1);
            l1.setLine(499-l1.getX1(), l1.getY1(), 499-l1.getX2(), l1.getY2());
            _demo1.tamgiacContainer.set(chonLua+1, l1);
               Line2D l2 = _demo1.tamgiacContainer.get(chonLua+2);
            l2.setLine(499-l2.getX1(),l2.getY1(), 499-l2.getX2(),  l2.getY2());
            _demo1.tamgiacContainer.set(chonLua+2, l2);
            _jp.update(_g2);
            _demo1.DrawAll();
    }//GEN-LAST:event_btnDXYActionPerformed

    private void btnDXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDXTActionPerformed
        // TODO add your handling code here:
          int doDich = Integer.parseInt(txtChiSo.getText());
           int chonLua = 3*(Integer.parseInt(txtChonHinh.getText())-1);
        // chonLua+=2;
        
            Line2D l = _demo1.tamgiacContainer.get(chonLua);
            l.setLine(499-l.getX1(),499- l.getY1(), 499-l.getX2(), 499-l.getY2());
            _demo1.tamgiacContainer.set(chonLua, l);
             Line2D l1 = _demo1.tamgiacContainer.get(chonLua+1);
            l1.setLine(499-l1.getX1(),499- l1.getY1(), 499-l1.getX2(),499- l1.getY2());
            _demo1.tamgiacContainer.set(chonLua+1, l1);
               Line2D l2 = _demo1.tamgiacContainer.get(chonLua+2);
            l2.setLine(499-l2.getX1(),499- l2.getY1(),499- l2.getX2(), 499 - l2.getY2());
            _demo1.tamgiacContainer.set(chonLua+2, l2);
            _jp.update(_g2);
            _demo1.DrawAll();
            
    }//GEN-LAST:event_btnDXTActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDL;
    private javax.swing.JButton btnDP;
    private javax.swing.JButton btnDT;
    private javax.swing.JButton btnDX;
    private javax.swing.JButton btnDXT;
    private javax.swing.JButton btnDXX;
    private javax.swing.JButton btnDXY;
    private javax.swing.JButton btnDichLen;
    private javax.swing.JButton btnDichPhai;
    private javax.swing.JButton btnDichTrai;
    private javax.swing.JButton btnDichXuong;
    private javax.swing.JButton btnDxOX;
    private javax.swing.JButton btnDxOY;
    private javax.swing.JButton btnDxQT;
    private javax.swing.JButton btnVeTamGiac;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtChiSo;
    private javax.swing.JTextField txtChonHinh;
    private javax.swing.JTextField txtChonLua;
    private javax.swing.JTextField txtD;
    private javax.swing.JTextField txtX1;
    private javax.swing.JTextField txtX2;
    private javax.swing.JTextField txtY1;
    private javax.swing.JTextField txtY2;
    private javax.swing.JTextField txtYc;
    private javax.swing.JTextField txtdoDich;
    private javax.swing.JTextField txtxA;
    private javax.swing.JTextField txtxB;
    private javax.swing.JTextField txtxC;
    private javax.swing.JTextField txtyA;
    private javax.swing.JTextField txtyB;
    // End of variables declaration//GEN-END:variables
}
