/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo;

import java.awt.Graphics2D;
import java.util.List;
import java.awt.geom.Line2D;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author hoangthang
 */
public class frmve3D extends javax.swing.JFrame {

    /**
     * Creates new form frmve3D
     */
    public frmve3D() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtCC = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtX = new javax.swing.JTextField();
        txtY = new javax.swing.JTextField();
        txtZ = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCD = new javax.swing.JTextField();
        txtCR = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtxA = new javax.swing.JTextField();
        txtyA = new javax.swing.JTextField();
        txtZa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtXA = new javax.swing.JTextField();
        txtYA = new javax.swing.JTextField();
        txtZA = new javax.swing.JTextField();
        txtH = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtD = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/270f.png"))); // NOI18N
        jButton1.setText("Vẽ ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Đỉnh A");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Chiều dài :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Chiều rộng : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Chiều cao :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtX, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(txtY, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtZ, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(txtCD, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtCR, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCC, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addContainerGap(26, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hình hộp chữ nhật", jPanel1);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Đỉnh A");

        txtxA.setText("10");

        txtyA.setText("20");

        txtZa.setText("30");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Cạnh A");

        txtA.setText("40");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/270f.png"))); // NOI18N
        jButton2.setText("Vẽ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtxA, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtyA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtZa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtxA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtyA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtZa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hình lập phương", jPanel2);

        jLabel8.setText("Đỉnh A");

        jLabel9.setText("Chiều cao h");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/270f.png"))); // NOI18N
        jButton3.setText("Vẽ ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setText("Độ dài d");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtXA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtYA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtD, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtZA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtXA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtZA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(102, 102, 102))
        );

        jTabbedPane1.addTab("Hình chóp", jPanel3);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3d_4.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel10)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private JPanel _jp;
    public void setjpanel(JPanel jp)
    {
        _jp=jp;
    }
    private Demo1 _demo1;
    public void setFrmDemo(Demo1 d1)
    {
        _demo1 = d1;
    }
   private Line2D lineBuffer;
    Graphics2D _g2;
    public void setG2(Graphics2D g2){
        _g2 = g2;
    }
    public List<Line2D> hhcnContainer = new ArrayList();
    public List<Line2D> hcContainer = new ArrayList();
     public  void netdut(float xbd,float ybd,float xkt,float ykt)
    {
        float j=ybd;
        if(xbd<xkt&&ybd<ykt)
        {
            for(float i = xbd;i<xkt;i=i + 6)
            {
                lineBuffer = new Line2D.Float((float)i, (float)j, (float)i+3, (float)j+3);
                hhcnContainer.add(lineBuffer);
                j = j+6;
             }  
        
        } 
        if(xbd>xkt&&ybd<ykt)
        {
            for(float i = xbd;i>xkt;i=i - 6)
            {
                lineBuffer = new Line2D.Float((float)i, (float)j, (float)i-3, (float)j+3);
                hhcnContainer.add(lineBuffer);
                j = j+6;
             }         
        }
        if(xbd<xkt&&ybd>ykt)
        {
            for(float i = xbd;i<xkt;i=i + 6)
            {
                lineBuffer = new Line2D.Float((float)i, (float)j, (float)i+3, (float)j-3);
                hhcnContainer.add(lineBuffer);
                j = j-6;
             }  
            //g2.setColor(mau);
        } 
        if(xbd>xkt&&ybd>ykt)
        {
            for(float i = xbd;i>xkt;i=i - 6)
            {
                lineBuffer = new Line2D.Float((float)i, (float)j, (float)i-3, (float)j-3);
                hhcnContainer.add(lineBuffer);
                j = j-6;
             }  
           
        }
        if(xbd==xkt&&ybd<ykt)
        {
            for(float i = ybd;i<ykt;i=i + 6)
            {
                lineBuffer = new Line2D.Float((float)xbd, (float)i, (float)xbd, (float)i+3);
                hhcnContainer.add(lineBuffer);
                //j = j+10;
             }  
            //g2.setColor(mau);
        }
        if(xbd==xkt&&ybd>ykt)
        {
            for(float i = ybd;i>ykt;i=i - 6)
            {
                lineBuffer = new Line2D.Float((float)xbd, (float)i, (float)xbd, (float)i-3);
                hhcnContainer.add(lineBuffer);
                //j = j-10;
             }  
            //g2.setColor(mau);
        }
        if(xbd<xkt&&ybd==ykt)
        {
            for(float i = xbd;i<xkt;i=i + 6)
            {
                lineBuffer = new Line2D.Float((float)i, (float)ybd, (float)i+3, (float)ybd);
                hhcnContainer.add(lineBuffer);
                //j = j-10;
             }  
            //g2.setColor(mau);
        }
        if(xbd>xkt&&ybd==ykt)
        {
            for(float i = xbd;i>xkt;i=i - 6)
            {
                lineBuffer = new Line2D.Float((float)i, (float)ybd, (float)i-3, (float)ybd);
                hhcnContainer.add(lineBuffer);
                //j = j-10;
             }  
            //g2.setColor(mau);
        }
    }
        
    public void VeLine(float x1,float y1,float x2,float y2)
    {
       lineBuffer = new Line2D.Float(x1, y1, x2, y2);
       hhcnContainer.add(lineBuffer);
    }
    public void VeHHCN(int x1,int y1,int z1,int cd,int cr,int cc)
    {
        
        float x = -TinhxOfz(x1, y1, z1)+250;
        float y = 250+z1-cc;
        
        VeLine(x, y, x+cr, y);
        netdut((int)x, (int)y, (int)x, (int)y+cc);
        VeLine(x, y, x-cd, y+cd);
        VeLine(x-cd, y+cd, x-cd, y+cd+cc);
        netdut(x-cd, y+cd+cc, x, y+cc);
        netdut(x, y+cc,x+cr,y+cc);
        VeLine(x+cr,y+cc, x+cr, y);
        VeLine (x+cr, y,x+cr-cd,y+cd);
        VeLine (x+cr-cd,y+cd,x-cd,y+cd);
         VeLine (x+cr-cd,y+cd,x+cr-cd,y+cd+cc);
         VeLine (x+cr-cd,y+cd+cc,x-cd,y+cd+cc);
         VeLine (x+cr-cd,y+cd+cc,x+cr,y+cc);
    }
     public void VeHLP(int x1,int y1,int z1,int a)
    {
       // hhcnContainer.clear();
        float x = -TinhxOfz(x1, y1, z1)+250;
        float y = 250+z1-a;
        //float xt = 0, yt = 0;
        VeLine(x, y, x+a, y);
        netdut(x, y, x, y+a);
        VeLine(x, y, x-a/2, y+a/2);
        VeLine(x-a/2, y+a/2,x-a/2,y+a/2+a);
        netdut(x-a/2,y+a/2+a, x, y+a);
        netdut(x,y+a,x+a,y+a);
        VeLine(x+a,y+a, x+a, y);
        VeLine(x+a, y, x+a-a/2, y+a/2);
        VeLine(x+a-a/2, y+a/2, x-a/2, y+a/2);
        VeLine(x+a-a/2, y+a/2, x+a-a/2, y+a/2+a);
        VeLine(x+a-a/2, y+a/2+a,x-a/2,y+a+a/2);
         VeLine(x+a-a/2, y+a/2+a,x+a,y+a);
       
    }
    private void VeHC(int xa,int ya,int za,int d,int h)
    {
         float x = -TinhxOfz(xa, ya, za)+250;
        float y = 250+za-d;
        
        netdut(x, y, x+d, y);
        VeLine( x+d, y,x+d-d/2,y+d/2);
         VeLine(x+d-d/2,y+d/2,x-d/2,y+d/2);
         netdut(x-d/2,y+d/2, x, y);
         netdut(x,y,x,y-h);
         VeLine(x,y-h, x+d, y);
          VeLine(x,y-h, x+d-d/2, y+d/2);
         VeLine(x,y-h, x-d/2,y+d/2 );
        
        
    }
    
    public void DrawAll()
    {
       _jp.update(_g2);
        for(int i = 0 ; i <hhcnContainer.size();i++)
        {
            _g2.draw(hhcnContainer.get(i));
        }
        for(int i = 0 ; i <_demo1.xyzContainer.size();i++)
        {
            _g2.draw(_demo1.xyzContainer.get(i));
        }
    }
    public float TinhxOfz(int x,int y,int z)
    { 
        return z-y+x;
    }
            
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int x = Integer.parseInt(txtX.getText());
        int y = Integer.parseInt(txtY.getText());
        int z = Integer.parseInt(txtZ.getText());
        int cd = Integer.parseInt(txtCD.getText());
        int cr = Integer.parseInt(txtCR.getText());
         int cc = Integer.parseInt(txtCC.getText());
        VeHHCN(x, y, z, cd, cr, cc);
        DrawAll();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int x = Integer.parseInt(txtxA.getText());
        int y = Integer.parseInt(txtyA.getText());
        int z = Integer.parseInt(txtZa.getText());
        int a = Integer.parseInt(txtA.getText());
        
        VeHLP(x, y, z, a);
        DrawAll();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here
        int x = Integer.parseInt(txtXA.getText());
        int y = Integer.parseInt(txtYA.getText());
        int z = Integer.parseInt(txtZA.getText());
        int h = Integer.parseInt(txtH.getText());
        int d = Integer.parseInt(txtD.getText());
        
        VeHC( x, y, z, d,h);
        DrawAll();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtCC;
    private javax.swing.JTextField txtCD;
    private javax.swing.JTextField txtCR;
    private javax.swing.JTextField txtD;
    private javax.swing.JTextField txtH;
    private javax.swing.JTextField txtX;
    private javax.swing.JTextField txtXA;
    private javax.swing.JTextField txtY;
    private javax.swing.JTextField txtYA;
    private javax.swing.JTextField txtZ;
    private javax.swing.JTextField txtZA;
    private javax.swing.JTextField txtZa;
    private javax.swing.JTextField txtxA;
    private javax.swing.JTextField txtyA;
    // End of variables declaration//GEN-END:variables
}
