/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo;
import java.awt.Graphics2D;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;
import java.awt.geom.Point2D;
import java.awt.geom.Rectangle2D;
import java.util.List;
import java.util.Set;
import javafx.scene.shape.Arc;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author hoangthang
 */
public class frmXuLiDich extends javax.swing.JFrame {

    /**
     * Creates new form frmXuLiDich
     */
    public frmXuLiDich() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDichPhai = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtDodich = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCDuongThang = new javax.swing.JTextField();
        btnDichTrai = new javax.swing.JButton();
        btnDichLen = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnDx0x = new javax.swing.JButton();
        dx0y = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Phép biến đổi");

        btnDichPhai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDichPhai.setText("Dịch Phải");
        btnDichPhai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDichPhaiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Chỉ số thay đổi");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Chọn hình số");

        btnDichTrai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDichTrai.setText("Dịch trái");
        btnDichTrai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDichTraiActionPerformed(evt);
            }
        });

        btnDichLen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDichLen.setText("Dịch xuống ");
        btnDichLen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDichLenActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Dịch lên");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnDx0x.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDx0x.setText("Đối xứng qua 0x");
        btnDx0x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDx0xActionPerformed(evt);
            }
        });

        dx0y.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dx0y.setText("Đối xứng qua Oy");
        dx0y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dx0yActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("Tỷ lệ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setText("Quay quanh tâm");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Đối xứng qua tâm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/move.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDichPhai)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtDodich, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(btnDichTrai)
                                        .addComponent(btnDichLen))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(txtCDuongThang, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dx0y)
                            .addComponent(btnDx0x)
                            .addComponent(jButton4)
                            .addComponent(jButton7)
                            .addComponent(jButton1)
                            .addComponent(jButton8))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDodich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCDuongThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDichPhai)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDichTrai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDichLen))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDx0x)
                .addGap(18, 18, 18)
                .addComponent(dx0y)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   private JPanel _jp;
    public void setjpanel(JPanel jp)
    {
        _jp=jp;
    }
    Graphics2D _g2;
    public void setG2(Graphics2D g2){
        _g2 = g2;
    }
    private Demo1 _demo1;
    public void setFrmDemo(Demo1 d1)
    {
        _demo1 = d1;
    }
    private void btnDichPhaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDichPhaiActionPerformed
        // TODO add your handling code here:
        int doDich = Integer.parseInt(txtDodich.getText());
        int chonDgThg = Integer.parseInt(txtCDuongThang.getText())-1;
        
       if(_demo1.getRadioLine().isSelected()){
           chonDgThg+=2;
            Line2D l = _lineContainer.get(chonDgThg);
            l.setLine(l.getX1()+doDich, l.getY1(), l.getX2()+doDich, l.getY2());
            _lineContainer.set(chonDgThg, l);
            _jp.update(_g2);
            
            
       }
       
       if(_demo1.getRadioCir().isSelected()){
       Ellipse2D e = _cirContainer.get(chonDgThg);
       e.setFrame(e.getX()+doDich,e.getY(),e.getWidth(),e.getHeight());
      _cirContainer.set(chonDgThg, e);
       _jp.update(_g2);
      
       }
          if(_demo1.getRadioHv().isSelected()){
       Rectangle2D hv = _demo1.hvContainer.get(chonDgThg);
       hv.setFrame(hv.getX()+doDich,hv.getY(),hv.getWidth(),hv.getHeight());
      _demo1.hvContainer.set(chonDgThg, hv);
       _jp.update(_g2);
      
       }
           if(_demo1.getRadioEllip().isSelected()){
       Ellipse2D el = _demo1.elipContainer.get(chonDgThg);
       el.setFrame(el.getX()+doDich,el.getY(),el.getWidth(),el.getHeight());
      _demo1.elipContainer.set(chonDgThg, el);
       _jp.update(_g2);
      
       }
              if(_demo1.getRadioHcn().isSelected()){
       Rectangle2D hcn = _demo1.hcnContainer.get(chonDgThg);
       hcn.setFrame(hcn.getX()+doDich,hcn.getY(),hcn.getWidth(),hcn.getHeight());
      _demo1.hcnContainer.set(chonDgThg, hcn);
       _jp.update(_g2);
      }
       _demo1.DrawAll();
       
        
    }//GEN-LAST:event_btnDichPhaiActionPerformed

    private void btnDx0xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDx0xActionPerformed
        // TODO add your handling code here:
        int chonDgThg = Integer.parseInt(txtCDuongThang.getText())-1;
          if(_demo1.getRadioLine().isSelected()){
              chonDgThg+=2;
            Line2D l = _lineContainer.get(chonDgThg);
            l.setLine(l.getX1(),499-l.getY1(), l.getX2(),499- l.getY2());
            _lineContainer.set(chonDgThg, l);
            _jp.update(_g2);
       }
          if(_demo1.getRadioCir().isSelected()){
       Ellipse2D e = _cirContainer.get(chonDgThg);
       e.setFrame(e.getX(),500-e.getY()-e.getWidth(),e.getWidth(),e.getHeight());
      _cirContainer.set(chonDgThg,e);
       _jp.update(_g2);
      
       }
           if(_demo1.getRadioHv().isSelected()){
       Rectangle2D hv = _demo1.hvContainer.get(chonDgThg);
       hv.setFrame(hv.getX(),500-hv.getY()-hv.getWidth(),hv.getWidth(),hv.getHeight());
      _demo1.hvContainer.set(chonDgThg,hv);
       _jp.update(_g2);
      
       }
            if(_demo1.getRadioEllip().isSelected())
       {
       Ellipse2D el = _demo1.elipContainer.get(chonDgThg);
       el.setFrame(el.getX(),500-el.getY()-el.getHeight(),el.getWidth(),el.getHeight());
      _demo1.elipContainer.set(chonDgThg,el);
       _jp.update(_g2);
      
       }
                if(_demo1.getRadioHcn().isSelected()){
       Rectangle2D cn = _demo1.hcnContainer.get(chonDgThg);
       cn.setFrame(cn.getX(),500-cn.getY()-cn.getHeight(),cn.getWidth(),cn.getHeight());
      _demo1.hcnContainer.set(chonDgThg,cn);
       _jp.update(_g2);
      }
       _demo1.DrawAll();
    }//GEN-LAST:event_btnDx0xActionPerformed
    private float HeSoLine(Line2D l)
    {
        return (float) ((l.getY1()-l.getY2())/(l.getX1()-l.getX2()));
    }
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int doDich = Integer.parseInt(txtDodich.getText());
         int chonDgThg = Integer.parseInt(txtCDuongThang.getText())-1;
          if(_demo1.getRadioLine().isSelected()){
              chonDgThg+=2;
            Line2D l = _lineContainer.get(chonDgThg);
            float k = HeSoLine(l);
            if(l.getX1()>l.getX2())
            l.setLine(l.getX1()+doDich,l.getY1()+k*doDich, l.getX2()-doDich,l.getY2()-k*doDich);
            else
                l.setLine(l.getX1()-doDich,l.getY1()-k*doDich, l.getX2()+doDich,l.getY2()+k*doDich);
            _lineContainer.set(chonDgThg, l);
            _jp.update(_g2);
       }
          if(_demo1.getRadioCir().isSelected()){
       Ellipse2D e = _cirContainer.get(chonDgThg);
       e.setFrame(e.getX(),e.getY(),e.getWidth()+doDich,e.getHeight()+doDich);
      _cirContainer.set(chonDgThg,e);
       _jp.update(_g2);
      
       }
          if(_demo1.getRadioHv().isSelected()){
       Rectangle2D hv = _demo1.hvContainer.get(chonDgThg);
       hv.setFrame(hv.getX(),hv.getY(),hv.getWidth()+doDich,hv.getHeight()+doDich);
      _demo1.hvContainer.set(chonDgThg,hv);
       _jp.update(_g2);
      
       }
        if(_demo1.getRadioEllip().isSelected()){
       Ellipse2D e1 = _demo1.elipContainer.get(chonDgThg);
       e1.setFrame(e1.getX(),e1.getY(),e1.getWidth()+doDich,e1.getHeight()+doDich);
     _demo1.elipContainer.set(chonDgThg,e1);
       _jp.update(_g2);}
        
        if(_demo1.getRadioHcn().isSelected()){
       Rectangle2D hv1 = _demo1.hcnContainer.get(chonDgThg);
       hv1.setFrame(hv1.getX(),hv1.getY(),hv1.getWidth()+doDich,hv1.getHeight()+doDich);
      _demo1.hcnContainer.set(chonDgThg,hv1);
       _jp.update(_g2);
      
       }
          _demo1.DrawAll();
    }//GEN-LAST:event_jButton7ActionPerformed
    
    private void btnDichTraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDichTraiActionPerformed
        // TODO add your handling code here:
           int doDich = Integer.parseInt(txtDodich.getText());
        int chonDgThg = Integer.parseInt(txtCDuongThang.getText())-1;
        
       if(_demo1.getRadioLine().isSelected()){
           chonDgThg+=2;
            Line2D l = _lineContainer.get(chonDgThg);
            l.setLine(l.getX1()-doDich, l.getY1(), l.getX2()-doDich, l.getY2());
            _lineContainer.set(chonDgThg, l);
            _jp.update(_g2);
            
            
       }
       
       if(_demo1.getRadioCir().isSelected()){
       Ellipse2D e = _cirContainer.get(chonDgThg);
       e.setFrame(e.getX()-doDich,e.getY(),e.getWidth(),e.getHeight());
      _cirContainer.set(chonDgThg, e);
       _jp.update(_g2);
      
       }
          if(_demo1.getRadioHv().isSelected()){
       Rectangle2D hv = _demo1.hvContainer.get(chonDgThg);
       hv.setFrame(hv.getX()-doDich,hv.getY(),hv.getWidth(),hv.getHeight());
      _demo1.hvContainer.set(chonDgThg, hv);
       _jp.update(_g2);
      
       }
           if(_demo1.getRadioEllip().isSelected()){
       Ellipse2D el = _demo1.elipContainer.get(chonDgThg);
       el.setFrame(el.getX()-doDich,el.getY(),el.getWidth(),el.getHeight());
      _demo1.elipContainer.set(chonDgThg, el);
       _jp.update(_g2);
      
       }
              if(_demo1.getRadioHcn().isSelected()){
       Rectangle2D hcn = _demo1.hcnContainer.get(chonDgThg);
       hcn.setFrame(hcn.getX()-doDich,hcn.getY(),hcn.getWidth(),hcn.getHeight());
      _demo1.hcnContainer.set(chonDgThg, hcn);
       _jp.update(_g2);
      }
       _demo1.DrawAll();
    }//GEN-LAST:event_btnDichTraiActionPerformed

    private void btnDichLenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDichLenActionPerformed
        // TODO add your handling code here:
            int doDich = Integer.parseInt(txtDodich.getText());
        int chonDgThg = Integer.parseInt(txtCDuongThang.getText())-1;
        
       if(_demo1.getRadioLine().isSelected()){
           chonDgThg+=2;
            Line2D l = _lineContainer.get(chonDgThg);
            l.setLine(l.getX1(), l.getY1()+doDich, l.getX2(), l.getY2()+doDich);
            _lineContainer.set(chonDgThg, l);
            _jp.update(_g2);
            
            
       }
       
       if(_demo1.getRadioCir().isSelected()){
       Ellipse2D e = _cirContainer.get(chonDgThg);
       e.setFrame(e.getX(),e.getY()+doDich,e.getWidth(),e.getHeight());
      _cirContainer.set(chonDgThg, e);
       _jp.update(_g2);
      
       }
          if(_demo1.getRadioHv().isSelected()){
       Rectangle2D hv = _demo1.hvContainer.get(chonDgThg);
       hv.setFrame(hv.getX(),hv.getY()+doDich,hv.getWidth(),hv.getHeight());
      _demo1.hvContainer.set(chonDgThg, hv);
       _jp.update(_g2);
      
       }
           if(_demo1.getRadioEllip().isSelected()){
       Ellipse2D el = _demo1.elipContainer.get(chonDgThg);
       el.setFrame(el.getX(),el.getY()+doDich,el.getWidth(),el.getHeight());
      _demo1.elipContainer.set(chonDgThg, el);
       _jp.update(_g2);
      
       }
              if(_demo1.getRadioHcn().isSelected()){
       Rectangle2D hcn = _demo1.hcnContainer.get(chonDgThg);
       hcn.setFrame(hcn.getX(),hcn.getY()+doDich,hcn.getWidth(),hcn.getHeight());
      _demo1.hcnContainer.set(chonDgThg, hcn);
       _jp.update(_g2);
      }
       _demo1.DrawAll();
    }//GEN-LAST:event_btnDichLenActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
              int doDich = Integer.parseInt(txtDodich.getText());
        int chonDgThg = Integer.parseInt(txtCDuongThang.getText())-1;
        
       if(_demo1.getRadioLine().isSelected()){
           chonDgThg+=2;
            Line2D l = _lineContainer.get(chonDgThg);
            l.setLine(l.getX1(), l.getY1()-doDich, l.getX2(), l.getY2()-doDich);
            _lineContainer.set(chonDgThg, l);
            _jp.update(_g2);
            
            
       }
       
       if(_demo1.getRadioCir().isSelected()){
       Ellipse2D e = _cirContainer.get(chonDgThg);
       e.setFrame(e.getX(),e.getY()-doDich,e.getWidth(),e.getHeight());
      _cirContainer.set(chonDgThg, e);
       _jp.update(_g2);
      
       }
          if(_demo1.getRadioHv().isSelected()){
       Rectangle2D hv = _demo1.hvContainer.get(chonDgThg);
       hv.setFrame(hv.getX(),hv.getY()-doDich,hv.getWidth(),hv.getHeight());
      _demo1.hvContainer.set(chonDgThg, hv);
       _jp.update(_g2);
      
       }
           if(_demo1.getRadioEllip().isSelected()){
       Ellipse2D el = _demo1.elipContainer.get(chonDgThg);
       el.setFrame(el.getX(),el.getY()-doDich,el.getWidth(),el.getHeight());
      _demo1.elipContainer.set(chonDgThg, el);
       _jp.update(_g2);
      
       }
              if(_demo1.getRadioHcn().isSelected()){
       Rectangle2D hcn = _demo1.hcnContainer.get(chonDgThg);
       hcn.setFrame(hcn.getX(),hcn.getY()-doDich,hcn.getWidth(),hcn.getHeight());
      _demo1.hcnContainer.set(chonDgThg, hcn);
       _jp.update(_g2);
      }
       _demo1.DrawAll();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void dx0yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dx0yActionPerformed
        // TODO add your handling code here:
         int chonDgThg = Integer.parseInt(txtCDuongThang.getText())-1;
          if(_demo1.getRadioLine().isSelected()){
              chonDgThg+=2;
            Line2D l = _lineContainer.get(chonDgThg);
            l.setLine(499-l.getX1(),l.getY1(),499- l.getX2(), l.getY2());
            _lineContainer.set(chonDgThg, l);
            _jp.update(_g2);
       }
          if(_demo1.getRadioCir().isSelected()){
       Ellipse2D e = _cirContainer.get(chonDgThg);
       e.setFrame(500-e.getX()-e.getWidth(),e.getY(),e.getWidth(),e.getHeight());
      _cirContainer.set(chonDgThg,e);
       _jp.update(_g2);
      
       }
           if(_demo1.getRadioHv().isSelected()){
       Rectangle2D hv = _demo1.hvContainer.get(chonDgThg);
       hv.setFrame(500-hv.getX()-hv.getWidth(),hv.getY(),hv.getWidth(),hv.getHeight());
      _demo1.hvContainer.set(chonDgThg,hv);
       _jp.update(_g2);
      
       }
            if(_demo1.getRadioEllip().isSelected()){
       Ellipse2D el = _demo1.elipContainer.get(chonDgThg);
       el.setFrame(500-el.getX()-el.getWidth(),el.getY(),el.getWidth(),el.getHeight());
      _demo1.elipContainer.set(chonDgThg,el);
       _jp.update(_g2);
      
       }
                if(_demo1.getRadioHcn().isSelected()){
       Rectangle2D cn = _demo1.hcnContainer.get(chonDgThg);
       cn.setFrame(500-cn.getX()-cn.getWidth(),cn.getY(),cn.getWidth(),cn.getHeight());
      _demo1.hcnContainer.set(chonDgThg,cn);
       _jp.update(_g2);
      }
       _demo1.DrawAll();
    }//GEN-LAST:event_dx0yActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         int chonDgThg = Integer.parseInt(txtCDuongThang.getText())-1;
          if(_demo1.getRadioLine().isSelected()){
              chonDgThg+=2;
            Line2D l = _lineContainer.get(chonDgThg);
            l.setLine(499-l.getX1(),499- l.getY1(),499- l.getX2(),499- l.getY2());
            _lineContainer.set(chonDgThg, l);
            _jp.update(_g2);
       }
          if(_demo1.getRadioCir().isSelected()){
       Ellipse2D e = _cirContainer.get(chonDgThg);
       e.setFrame(500-e.getX()-e.getWidth(),500-e.getY()-e.getWidth(),e.getWidth(),e.getHeight());
      _cirContainer.set(chonDgThg,e);
       _jp.update(_g2);
      
       }
           if(_demo1.getRadioHv().isSelected()){
       Rectangle2D hv = _demo1.hvContainer.get(chonDgThg);
       hv.setFrame(500-hv.getX()-hv.getWidth(),500-hv.getY()-hv.getWidth(),hv.getWidth(),hv.getHeight());
      _demo1.hvContainer.set(chonDgThg,hv);
       _jp.update(_g2);
      
       }
         if(_demo1.getRadioEllip().isSelected()){
       Ellipse2D el = _demo1.elipContainer.get(chonDgThg);
       el.setFrame(500-el.getX()-el.getWidth(),500-el.getY()-el.getWidth(),el.getWidth(),el.getHeight());
      _demo1.elipContainer.set(chonDgThg,el);
       _jp.update(_g2);
      
       }
                if(_demo1.getRadioHcn().isSelected()){
       Rectangle2D cn = _demo1.hcnContainer.get(chonDgThg);
       cn.setFrame(500-cn.getX()-cn.getWidth(),500-cn.getY()-cn.getWidth(),cn.getWidth(),cn.getHeight());
      _demo1.hcnContainer.set(chonDgThg,cn);
       _jp.update(_g2);
      }
          _demo1.DrawAll();

    }//GEN-LAST:event_jButton1ActionPerformed
    public float ChuyenX(float x)
    {
       
        return x - 250;
        
    }
    public float ChuyenY(float y)
    {
       
        return 250-y ;
    }

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
       //   int doDich = Integer.parseInt(txtDodich.getText());
        int chonDgThg = Integer.parseInt(txtCDuongThang.getText())-1; 
            double sin = Math.sin(Math.PI * 45.0/180.0);
            double cos = Math.cos(Math.PI * 45.0/180.0);
        
       if(_demo1.getRadioLine().isSelected()){
           chonDgThg+=2;
          Line2D l = _lineContainer.get(chonDgThg);
         /*   l.setLine( ChuyenX((float) l.getX1()), ChuyenY((float) l.getY1()),-ChuyenY((float) l.getY2()), ChuyenX((float) l.getX2()));
            _lineContainer.set(chonDgThg, l);*/
          
            int x1 =   (int)(ChuyenX((float) l.getX1()));
            int y1 =  (int) (ChuyenY((float) l.getY1()));
            int x2 =  (int) (ChuyenX((float) l.getX2()));
            int y2 =  (int) (ChuyenY((float) l.getY2()));
         //  JOptionPane.showMessageDialog(rootPane, x1 + " " + y1 + " " + x2 + " " + y2);
            int xA = (int) (x1 * cos - sin *y1);
            int yA = (int) (x1 * sin + cos *y1);
            int xB = (int) (x2 * cos - sin * y2);
            int yB = (int) (x2 * sin + cos * y2);
               //JOptionPane.showMessageDialog(rootPane, xA + " " + yA+ " " + xB + " " + yB);
            l.setLine(xA + 250 ,250-yA,xB + 250,250-yB);
               // l.setLine((int)l.getX1() * cos - sin * l.getY1(),);
                _lineContainer.set(chonDgThg, l);
            _jp.update(_g2);
        }
            if(_demo1.getRadioHv().isSelected()){
       Rectangle2D hv = _demo1.hvContainer.get(chonDgThg);
       
       
          int x2 =   (int)(ChuyenX((float) hv.getX()));
          int y2 =  (int) (ChuyenY((float) hv.getY()));
          int xHv = (int) (x2 * cos - sin *y2);
          int yHv = (int) (x2 * sin + cos *y2);
          
         hv.setFrame(xHv+250,250-yHv,hv.getWidth(),hv.getHeight());
      _demo1.hvContainer.set(chonDgThg,hv);
       _jp.update(_g2);
      
       }
             if(_demo1.getRadioCir().isSelected()){
       Ellipse2D e = _cirContainer.get(chonDgThg);
           int x3 =   (int)(ChuyenX((float) e.getX()));
          int y3 =  (int) (ChuyenY((float) e.getY()));
          int xHT = (int) (x3 * cos - sin *y3);
          int yHT = (int) (x3 * sin + cos *y3);
       
     e.setFrame(xHT + 250 ,250 - yHT,e.getWidth(),e.getHeight());
      _cirContainer.set(chonDgThg,e);
       _jp.update(_g2);
    }
             if(_demo1.getRadioEllip().isSelected()){
       Ellipse2D el = _demo1.elipContainer.get(chonDgThg);
          int x4 =   (int)(ChuyenX((float) el.getX()));
          int y4 =  (int) (ChuyenY((float) el.getY()));
          int xEL = (int) (x4 * cos - sin *y4);
          int yEL = (int) (x4 * sin + cos *y4);
       el.setFrame(xEL + 250,250-yEL,el.getWidth(),el.getHeight());
      _demo1.elipContainer.set(chonDgThg,el);
       _jp.update(_g2);
      }
             if(_demo1.getRadioHcn().isSelected()){
       Rectangle2D cn = _demo1.hcnContainer.get(chonDgThg);
        int x5 =   (int)(ChuyenX((float) cn.getX()));
          int y5 =  (int) (ChuyenY((float) cn.getY()));
          int xCN = (int) (x5 * cos - sin *y5);
          int yCN = (int) (x5 * sin + cos *y5);
         cn.setFrame(xCN + 250,250- yCN ,cn.getWidth(),cn.getHeight());
      _demo1.hcnContainer.set(chonDgThg,cn);
       _jp.update(_g2);
      } 
       _demo1.DrawAll();
        
        
    }//GEN-LAST:event_jButton8ActionPerformed
    private double TinhbanKinh(Line2D l)
    {
        return Math.sqrt(Math.pow(l.getX1()-l.getX2(),2)+Math.pow(l.getY1()-l.getY2(),2));
    }
    private void TinhXY(double R,Line2D l,int doDich)
    {
        double x = l.getX2()-l.getX1();
        double y = l.getY2()-l.getY1();
        double alpha = Math.toRadians(Math.toDegrees(Math.acos(x/R))+ doDich);
        //JOptionPane.showMessageDialog(rootPane, Math.toDegrees(Math.acos(x/R)));
       if(y>0) alpha=-alpha;
        x = R*Math.cos(alpha)+l.getX1();
        y = R*Math.sin(alpha)+l.getY1();
       l.setLine(l.getX1(),l.getY1(), x, y);
        
    }    private List<Line2D> _lineContainer;
    public void SetContainerLine(List<Line2D> lineContainer)
    {
        _lineContainer = lineContainer;
    }
    private List<Ellipse2D> _cirContainer;
    public void SetContainerCirle(List<Ellipse2D> cirContainer)
    {
        _cirContainer = cirContainer;
    }
   
    
    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDichLen;
    private javax.swing.JButton btnDichPhai;
    private javax.swing.JButton btnDichTrai;
    private javax.swing.JButton btnDx0x;
    private javax.swing.JButton dx0y;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtCDuongThang;
    private javax.swing.JTextField txtDodich;
    // End of variables declaration//GEN-END:variables
}
