/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo;

import java.awt.Graphics2D;
import javax.swing.JPanel;

/**
 *
 * @author HoangThang
 */
public class frmXoa extends javax.swing.JFrame {

    /**
     * Creates new form frmXoa
     */
    public frmXoa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jBrDuongThang = new javax.swing.JRadioButton();
        jBrHinhBinhHanh = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtChonHinh = new javax.swing.JTextField();
        btnXoa = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jbrDuongtron = new javax.swing.JRadioButton();
        jbrHinhVuon = new javax.swing.JRadioButton();
        jbrElip = new javax.swing.JRadioButton();
        jbRHCN = new javax.swing.JRadioButton();
        jbrTamGiac = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonGroup1.add(jBrDuongThang);
        jBrDuongThang.setText("Đường Thẳng");

        buttonGroup1.add(jBrHinhBinhHanh);
        jBrHinhBinhHanh.setText("Hình Bình Hành");

        jLabel1.setText("Chọn Hình");

        txtChonHinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChonHinhActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jbrDuongtron);
        jbrDuongtron.setText("Đường tròn");

        buttonGroup1.add(jbrHinhVuon);
        jbrHinhVuon.setText("Hình Vuông");

        buttonGroup1.add(jbrElip);
        jbrElip.setText("Elip");

        buttonGroup1.add(jbRHCN);
        jbRHCN.setText("Hình chữ nhật");

        buttonGroup1.add(jbrTamGiac);
        jbrTamGiac.setText("Tam giác");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbrTamGiac)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbrElip)
                                    .addComponent(jBrDuongThang))
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbrHinhVuon)
                                    .addComponent(jbRHCN)
                                    .addComponent(jbrDuongtron)))
                            .addComponent(jBrHinhBinhHanh)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnXoa)
                                .addGap(56, 56, 56)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtChonHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtChonHinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBrDuongThang)
                    .addComponent(jbrDuongtron))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbrElip)
                    .addComponent(jbrHinhVuon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBrHinhBinhHanh)
                    .addComponent(jbRHCN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbrTamGiac)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa)
                    .addComponent(jButton1))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Demo1 dm ;
    public void setform(Demo1 dm1)
    {
        dm = dm1;
    }
    JPanel jp;
      public void setJP(JPanel jp1)
    {
        jp = jp1;
    }
      Graphics2D g2;
      public void setGraphic(Graphics2D g21)
    {
        g2 = g21;
    }

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int Chon = Integer.parseInt(txtChonHinh.getText())+1;
        if(jBrDuongThang.isSelected())
        {
            dm.lineContainer.remove(Chon);
            jp.update(g2);
            dm.DrawAll();
            
        }
        if(jbrDuongtron.isSelected())
        {
            dm.cirContainer.remove(Chon-2);
            jp.update(g2);
            dm.DrawAll();
        }
         if(jbrHinhVuon.isSelected())
        {
            dm.hvContainer.remove(Chon-2);
            jp.update(g2);
            dm.DrawAll();
        }
          if(jbRHCN.isSelected())
        {
            dm.hcnContainer.remove(Chon-2);
            jp.update(g2);
            dm.DrawAll();
        }
          if(jbrElip.isSelected())
        {
            dm.elipContainer.remove(Chon-2);
            jp.update(g2);
            dm.DrawAll();
        }
         if(jBrHinhBinhHanh.isSelected())
        {
            Chon = 4*(Chon-2);
            for(int i = 0;i<4;i++){
            dm.binhhanhContainer.remove(Chon);
            }
            jp.update(g2);
            dm.DrawAll();
        }
            if(jbrTamGiac.isSelected())
        {
            Chon = 3*(Chon-2);
            for(int i = 0;i<3;i++){
            dm.tamgiacContainer.remove(Chon);
            }
            jp.update(g2);
            dm.DrawAll();
        }
       
    }//GEN-LAST:event_btnXoaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtChonHinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChonHinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChonHinhActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jBrDuongThang;
    private javax.swing.JRadioButton jBrHinhBinhHanh;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jbRHCN;
    private javax.swing.JRadioButton jbrDuongtron;
    private javax.swing.JRadioButton jbrElip;
    private javax.swing.JRadioButton jbrHinhVuon;
    private javax.swing.JRadioButton jbrTamGiac;
    private javax.swing.JTextField txtChonHinh;
    // End of variables declaration//GEN-END:variables
}
